[build]
  command = ""          # No build step required
  publish = "."         # Your root folder

[build.environment]
  SECRETS_SCAN_OMIT_PATHS = "js/firebase-config.js"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["nodemailer"]
